variables:
  buildScript: build.ps1 -Target Bootstrap-Docker -DockerImagePrefix $(imageName)-$(build.buildId) -CIBuildStr "YESIAMABOOLEANVALUEAZUREPIPELINEBUG"

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - powershell: $(buildScript)
- job: Windows
  pool:
    vmImage: 'win1803'
  steps:
  - powershell: $(buildScript)