strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  imageName: 'snapx:$(build.buildId)'

steps:
- script: /usr/bin/pwsh -f build.ps1 -Target Bootstrap-Docker -DockerAzureImageName $(imageName) -DockerAzurePipelineBuildStr "YESIAMABOOLEANVALUEAZUREPIPELINEBUG"
  displayName: 'docker build'