strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'win1803'

pool:
  vmImage: $(imageName)

variables:
  dockerImageName: '$(imageName)-$(build.buildId)'

steps:
- script: pwsh -f build.ps1 -Target Bootstrap-Docker -DockerImagePrefix $(dockerImageName) -CIBuildStr "YESIAMABOOLEANVALUEAZUREPIPELINEBUG"
  displayName: 'Docker build'