resources:
  containers:
  - container: build_container
    image: youpark.azurecr.io/snapx:latest
    endpoint: youpark

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

container: build_container