variables:
  buildScript: build.ps1 -Target Bootstrap-Docker -DockerImagePrefix $(build.buildId) -CIBuildStr "YESIAMABOOLEANVALUEAZUREPIPELINEBUG"

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: pwsh $(buildScript)
- job: Windows
  pool: youpark
    vmImage: 'vs2017-win2016'
  steps:
  - script: powershell -f $(buildScript)