variables:
  buildScript: build.ps1 -Target Bootstrap -DockerImagePrefix $(build.buildId) -CIBuildStr "YESIAMABOOLEANVALUEAZUREPIPELINEBUG"

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: pwsh $(buildScript)
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: Linux
      mergeTestResults: true
- job: Windows_Visual_Studio_2017
  pool: 
    name: Youpark
    vmImage: 'win1803'
  steps:
  - script: powershell -f $(buildScript) -VisualStudioVersion "15"
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: Windows_Visual_Studio_2017
      mergeTestResults: true
  - task: NuGetCommand@2
    displayName: Publish nuget packages to snapx myget feed
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'snapx-myget-feed'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg' 
