strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

variables:
  azureSubscriptionEndpoint: youpark
  azureContainerRegistry: youpark.azurecr.io
  cachedSnapxContainerName: 'snapx:latest'

steps:
- task: Docker@1
  displayName: Build using cached docker image
  inputs:
    command: run
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(cachedSnapxContainerName)