strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

variables:
  imageName: 'snapx:$(build.buildId)'

steps:
- script: /usr/bin/pwsh -f build.ps1 -Target Bootstrap -DockerAzureImageName $(imageName) -DockerAzurePipelineBuild $true
  displayName: 'docker build'