variables:
  buildScript: build.ps1 -Target Bootstrap-Docker -DockerImagePrefix $(build.buildId) -CIBuildStr "YESIAMABOOLEANVALUEAZUREPIPELINEBUG"

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: pwsh $(buildScript)
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: Linux
      mergeTestResults: true
- job: Windows_Visual_Studio_2019
  pool: 
    name: Youpark
    vmImage: 'win1803'
  steps:
  - script: powershell -f $(buildScript) -VisualStudioVersion 16
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: Windows
      mergeTestResults: true