name: snapx

on: push

env:
  DOTNET_VERSION: 3.1.300

jobs:

  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell:preview-ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
                  
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}            
      
      - name: Setup powershell
        run: dotnet tool update powershell --global
        
      - name: Build native dependencies
        run:  
          pwsh -command ".\$GITHUB_WORKSPACE\build.ps1" -Target Bootstrap -DockerImagePrefix ${{ github.run_id }} -CIBuild "1"
      
