name: snapx

on: push
          
jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build native dependencies
        run:  
          pwsh -command ".\$GITHUB_WORKSPACE\build.ps1" -Target Bootstrap -DockerImagePrefix ${{ github.run_id }} -CIBuild "1"
      
