name: snapx

on: push

env:
  GPR_VERSION: 0.1.125
  GITVERSION_VERSION: 5.3.4
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  FINTER_NUGET_FEED: https://nuget.pkg.github.com/fintermobilityas/index.json        

jobs:

  setup:    
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      SNAPX_VERSION: ${{ steps.set-version.outputs.SNAPX_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
        
      - id: set-version
        name: Setup GitVersion and set build version
        shell: pwsh
        run: |
          dotnet tool update GitVersion.Tool --global --version ${{ env.GITVERSION_VERSION }}
          $SNAPX_VERSION = (dotnet gitversion /showVariable NugetVersionv2) | out-string
          echo "::set-env name=SNAPX_VERSION::$SNAPX_VERSION"
          echo "::set-output name=SNAPX_VERSION::$SNAPX_VERSION"
            
  unix:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      SNAPX_VERSION: ${{ needs.setup.outputs.SNAPX_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
          lfs: true
          submodules: true

      - uses: azure/docker-login@v1
        name: Docker login github packages
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }} 
          password:  ${{secrets.GITHUB_TOKEN }}     
          
      - name: Build & Run Tests
        timeout-minutes: 10
        run:  
          pwsh -command ".\${{ env.GITHUB_WORKSPACE }}\build.ps1" Bootstrap-Unix -CIBuild -Version ${{ env.SNAPX_VERSION }}
    
      - name: Collect artifacts
        env:
          SNAPX_UNIX_SETUP_LINUX_X64_ZIP_REL_DIR: build/dotnet/linux-x64/Snap.Installer/netcoreapp3.1/Release/publish
          SNAPX_UNIX_CORERUN_REL_DIR: build/native/Unix/x86_64-linux-gcc/Release/Snap.CoreRun
          SNAPX_UNIX_PAL_REL_DIR: build/native/Unix/x86_64-linux-gcc/Release/Snap.CoreRun.Pal
          SNAPX_MINGW_CORERUN_REL_DIR: build/native/Unix/x86_64-w64-mingw32-gcc/Release/Snap.CoreRun
          SNAPX_MINGW_PAL_REL_DIR: build/native/Unix/x86_64-w64-mingw32-gcc/Release/Snap.CoreRun.Pal
          SNAPX_MINGW_TESTS_REL_DIR: build/native/Unix/x86_64-w64-mingw32-gcc/Release/Snap.CoreRun.Tests
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/${{ env.SNAPX_UNIX_SETUP_LINUX_X64_ZIP_REL_DIR }}
          cp ${{ github.workspace }}/${{ env.SNAPX_UNIX_SETUP_LINUX_X64_ZIP_REL_DIR }}/Setup-linux-x64.zip ${{ github.workspace }}/artifacts/${{ env.SNAPX_UNIX_SETUP_LINUX_X64_ZIP_REL_DIR }}/Setup-linux-x64.zip

          mkdir -p ${{ github.workspace }}/artifacts/${{ env.SNAPX_UNIX_CORERUN_REL_DIR }}
          cp ${{ github.workspace }}/${{ env.SNAPX_UNIX_CORERUN_REL_DIR }}/corerun ${{ github.workspace }}/artifacts/${{ env.SNAPX_UNIX_CORERUN_REL_DIR }}/corerun
          
          mkdir -p ${{ github.workspace }}/artifacts/${{ env.SNAPX_UNIX_PAL_REL_DIR }}
          cp ${{ github.workspace }}/${{ env.SNAPX_UNIX_PAL_REL_DIR }}/libpal.so ${{ github.workspace }}/artifacts/${{ env.SNAPX_UNIX_PAL_REL_DIR }}/libpal.so
          
          mkdir -p ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_CORERUN_REL_DIR }}
          cp ${{ github.workspace }}/${{ env.SNAPX_MINGW_CORERUN_REL_DIR }}/corerun.exe ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_CORERUN_REL_DIR }}/corerun.exe

          mkdir -p ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_PAL_REL_DIR }}
          cp ${{ github.workspace }}/${{ env.SNAPX_MINGW_PAL_REL_DIR }}/libpal.dll ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_PAL_REL_DIR }}/libpal.dll

          mkdir -p ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}
          cp ${{ github.workspace }}/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}/corerun.exe ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}/corerun.exe
          cp ${{ github.workspace }}/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}/corerun_demoapp.exe ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}/corerun_demoapp.exe
          cp ${{ github.workspace }}/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}/corerun_tests.exe ${{ github.workspace }}/artifacts/${{ env.SNAPX_MINGW_TESTS_REL_DIR }}/corerun_tests.exe

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: unix
          path: ${{ github.workspace }}/artifacts/**/*

      - name: Upload dotnet test results
        if: always()
        uses: MirrorNG/nunit-reporter@v1.0.9
        with:
          path: ${{ github.workspace }}/build/dotnet/TestResults/**/TestResults.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
  windows:
    runs-on: windows-latest
    needs: [setup, unix]
    env:
      SNAPX_VERSION: ${{ needs.setup.outputs.SNAPX_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
            token: ${{ secrets.FINTER_CI_PAT }}
            lfs: true
            submodules: true 

      - name: Setup dotnet using global.json
        uses: actions/setup-dotnet@v1.5.0

      - name: Download unix artifacts
        uses: actions/download-artifact@v2
        with:
          name: unix
          path: ${{ github.workspace }}

      - name: Build & Run Tests
        timeout-minutes: 10
        run:  
          pwsh -command ".\${{ env.GITHUB_WORKSPACE }}\build.ps1" Bootstrap-Windows -CIBuild -Version ${{ env.SNAPX_VERSION }}

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: nupkgs
          path: ${{ github.workspace }}/nupkgs/*.nupkg
       
      - name: Upload dotnet test results
        if: always()
        uses: MirrorNG/nunit-reporter@v1.0.9
        with:
          path: ${{ github.workspace }}/build/dotnet/TestResults/**/TestResults.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
  publish:
    runs-on: ubuntu-latest
    needs: [setup, unix, windows]
    env:
      SNAPX_VERSION: ${{ needs.setup.outputs.SNAPX_VERSION }}
    steps:
      - name: Setup gpr v${{ env.GPR_VERSION }} 
        shell: pwsh
        run: dotnet tool update gpr --global --version ${{ env.GPR_VERSION }}
        
      - name: Download nupkgs artifacts
        uses: actions/download-artifact@v2
        with:
          name: nupkgs
          path: ${{ github.workspace }}/nupkgs
            
      - name: Push nuget packages
        run: | 
          gpr push ${{ github.workspace }}/nupkgs/snapx.${{ env.SNAPX_VERSION }}.nupkg --api-key ${{ secrets.FINTER_NUGET_GITHUB_PACKAGES_TOKEN }}
          gpr push ${{ github.workspace }}/nupkgs/Snapx.Core.${{ env.SNAPX_VERSION }}.nupkg --api-key ${{ secrets.FINTER_NUGET_GITHUB_PACKAGES_TOKEN }}

      - name: Create github release tag
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.SNAPX_VERSION }}
          release_name: Release v${{ env.SNAPX_VERSION }}
          draft: true
          prerelease: false
